[theme]
base = "dark"
primaryColor = "#F6C945"
backgroundColor = "#080909"
secondaryBackgroundColor = "#151716"
textColor = "#F4F5F2"
borderColor = "#292D2A"
showWidgetBorder = true
baseRadius = "small"
buttonRadius = "small"
font = "sans-serif"
headingFont = "sans-serif"
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#111312"
secondaryBackgroundColor = "#1A1D1B"
textColor = "#F4F5F2"
borderColor = "#292D2A"
primaryColor = "#F6C945"
